webtalk_init -webtalk_dir T:/engs31/finalproject/vga_driver_part3/vga_driver_part3.sim/sim_1/behav/xsim/xsim.dir/vga_driver_part3_1_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 28 21:31:53 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2348494" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "05e9dc25-d23a-4feb-a92f-9b266901a6cc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "facb3b5ede244527a64ac56e2a26089b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13896_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3192022795 -regid "" -xml T:/engs31/finalproject/vga_driver_part3/vga_driver_part3.sim/sim_1/behav/xsim/xsim.dir/vga_driver_part3_1_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html T:/engs31/finalproject/vga_driver_part3/vga_driver_part3.sim/sim_1/behav/xsim/xsim.dir/vga_driver_part3_1_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm T:/engs31/finalproject/vga_driver_part3/vga_driver_part3.sim/sim_1/behav/xsim/xsim.dir/vga_driver_part3_1_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
