# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab5_files-1/lab5-17X.xdc

# IP: ip/blk_mem_gen_1_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet
